# Deploy to github pages.
name: Publish to Github pages

on:
  push:
    branches:
      - master  # Set branch to deploy html to

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build hugo site
        run: hugo -F --baseURL https://mythaxis.github.io/WorkSpace/

      - name: Deploy ./docs to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs